create extension if not exists pgcrypto;
create schema if not exists auth;
create table auth.users(id uuid primary key,email text);
create table auth.sessions(id uuid primary key,user_id uuid references auth.users(id));
create or replace function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create or replace function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
do $$ begin create role anon; exception when duplicate_object then null; end $$;
do $$ begin create role authenticated; exception when duplicate_object then null; end $$;
do $$ begin create role service_role; exception when duplicate_object then null; end $$;
create table public.districts(id uuid primary key default gen_random_uuid(),name text not null,slug text not null,is_active boolean default true,created_at timestamptz default now(),subscription_plan text,contact_name text,support_email text,billing_email text,billing_status text,renewal_date date,invoice_reference text);
create table public.tenants(id uuid primary key default gen_random_uuid(),name text not null,access_code text,status text default 'active',primary_admin_profile_id uuid,district_id uuid references public.districts(id),created_at timestamptz default now());
create table public.profiles(id uuid primary key references auth.users(id),tenant_id uuid references public.tenants(id),district_id uuid references public.districts(id),role text not null,created_at timestamptz default now(),auth_email text,is_active boolean default true);
alter table public.tenants add constraint tenants_primary_admin_profile_id_fkey foreign key(primary_admin_profile_id) references public.profiles(id);
create table public.students(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),student_id text,created_at timestamptz default now(),deleted_at timestamptz,deleted_by uuid,username text not null);
create table public.gear(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),name text,status text,notes text,created_at timestamptz default now(),barcode text,checked_out_by uuid references public.students(id),checked_out_at timestamptz,serial_number text,deleted_at timestamptz,deleted_by uuid);
create table public.gear_logs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),gear_id uuid not null references public.gear(id),checked_out_by uuid not null references public.students(id),action_type text,action_time timestamptz default now(),performed_by uuid,operation_id text);
create table public.gear_status_history(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),gear_id uuid not null references public.gear(id),status text,note text,changed_by uuid,changed_at timestamptz default now());
create table public.admin_audit_logs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),actor_id uuid,action_type text,entity_type text,entity_id uuid,metadata jsonb,created_at timestamptz default now());
create table public.rate_limits(tenant_id uuid not null,actor_id uuid not null,scope text not null,window_start timestamptz not null default now(),count integer default 0,primary key(tenant_id,actor_id,scope,window_start));
create table public.tenant_policies(tenant_id uuid primary key references public.tenants(id),max_admins integer,max_students integer,max_gear integer,barcode_pattern text,updated_by uuid,updated_at timestamptz default now(),checkout_due_hours integer default 72,escalation_level_1_hours integer default 120,escalation_level_2_hours integer default 168,escalation_level_3_hours integer default 240,account_category text default 'organization',plan_code text,feature_flags jsonb default '{}'::jsonb);
create table public.tenant_security_controls(tenant_id uuid primary key references public.tenants(id),force_reauth_after timestamptz,updated_by uuid,updated_at timestamptz default now());
create table public.tenant_admin_sessions(id uuid primary key default gen_random_uuid(),tenant_id uuid references public.tenants(id),profile_id uuid references public.profiles(id),device_id text,device_label text,user_agent text,login_method text,login_location text,general_location text,auth_session_id text,auth_token_hash text,auth_token_issued_at timestamptz,created_at timestamptz default now(),last_seen_at timestamptz default now(),revoked_at timestamptz,revoked_by uuid references public.profiles(id));
create table public.support_requests(id uuid primary key,requester_name text,reply_email text,subject text,category text,message text,source text,status text,created_at timestamptz,updated_at timestamptz);
create table public.district_support_requests(id uuid primary key,district_id uuid references public.districts(id),requester_name text,requester_email text,subject text,message text,status text,created_at timestamptz,updated_at timestamptz);
create table public.email_delivery_logs(id uuid primary key,tenant_id uuid,district_id uuid);
create table public.client_error_reports(id uuid primary key,tenant_context_id text,district_context_id text,is_district_host boolean,district_id text);
create table public.cookie_consent_records(id uuid primary key,profile_id uuid references public.profiles(id));
create or replace function public.current_tenant_id() returns uuid language sql stable as $$select tenant_id from public.profiles where id=auth.uid()$$;
create or replace function public.current_district_id() returns uuid language sql stable as $$select district_id from public.profiles where id=auth.uid()$$;
alter table public.profiles enable row level security;
create policy legacy_profile on public.profiles for select using(tenant_id=public.current_tenant_id() or district_id=public.current_district_id());
create materialized view public.super_reporting_tenant_metrics as select id tenant_id,name from public.tenants;
insert into public.districts(id,name,slug) values('10000000-0000-0000-0000-000000000001','Legacy District','legacy-district');
insert into public.tenants(id,name,access_code,district_id) values('20000000-0000-0000-0000-000000000001','Legacy Workspace','SECRET','10000000-0000-0000-0000-000000000001');
insert into auth.users(id,email) values('30000000-0000-0000-0000-000000000001','admin@example.test'),('30000000-0000-0000-0000-000000000002','account@example.test');
insert into public.profiles(id,tenant_id,district_id,role,auth_email) values('30000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','district_admin','admin@example.test'),('30000000-0000-0000-0000-000000000002','20000000-0000-0000-0000-000000000001',null,'tenant_user','account@example.test');
update public.tenants set primary_admin_profile_id='30000000-0000-0000-0000-000000000001';
