import { authClient } from "../../auth/client";
import { getAuthState, setSecondaryAuth } from "../../store/authState";
import { registerPrivilegedAdminStepUp } from "../privilegedStepUpService";
import { touchSuperAdminSession } from "../superOps/sessions";
import { refreshAuthFromSession } from "./sessionBootstrap";
import { signOut } from "./signOut";
import { clearPendingSuperAdminVerificationEmail } from "./sessionState";
import { sendLoginNotification } from "./workspaceLogin";

const requireSuperAdmin = async (loginMethod: "password" | "passkey") => {
  await refreshAuthFromSession();
  const current = getAuthState();
  if (current.role !== "super_admin") {
    await signOut({ bestEffort: true });
    throw new Error("Access denied.");
  }
  await registerPrivilegedAdminStepUp();
  setSecondaryAuth(true);
  clearPendingSuperAdminVerificationEmail();
  try {
    await touchSuperAdminSession({ loginMethod, loginLocation: "super_auth" });
  } catch {
    // Session tracking is best-effort and must not weaken successful auth.
  }
  return current;
};

export const superAdminLogin = async (
  email: string,
  password: string,
  turnstileToken: string,
) => {
  setSecondaryAuth(false);
  const result = await authClient.signIn.email(
    { email: email.trim().toLowerCase(), password },
    { headers: { "x-captcha-response": turnstileToken } },
  );
  if (result.error) throw new Error(result.error.message || "Invalid credentials.");

  // Better Auth withholds the full session until its TOTP/backup challenge is
  // complete, so the caller routes that state to /two-factor.
  await refreshAuthFromSession();
  if (!getAuthState().isAuthenticated) return { email, requiresTwoFactor: true };
  const current = await requireSuperAdmin("password");
  sendLoginNotification(null, { loginLocation: "super_admin_login" });
  return { email: current.email ?? email, requiresTwoFactor: false };
};

export const superAdminPasskeyLogin = async (options: {
  sendLoginNotification?: boolean;
  loginLocation?: "super_auth" | "super_settings";
} = {}) => {
  const result = await authClient.signIn.passkey();
  if (result.error) throw new Error(result.error.message || "Passkey sign in failed.");
  await refreshAuthFromSession();
  const current = getAuthState();
  if (current.role !== "super_admin") {
    await signOut({ bestEffort: true });
    throw new Error("Access denied.");
  }
  await registerPrivilegedAdminStepUp();
  setSecondaryAuth(true);
  clearPendingSuperAdminVerificationEmail();
  try {
    await touchSuperAdminSession({
      loginMethod: "passkey",
      loginLocation: options.loginLocation ?? "super_auth",
    });
  } catch {
    // Session tracking is best-effort and must not weaken successful auth.
  }
  if (options.sendLoginNotification !== false) {
    sendLoginNotification(null, { loginLocation: "super_admin_login" });
  }
};

/** @deprecated The UI now routes Better Auth challenges to /two-factor. */
export const verifySuperAdminEmailChallenge = async (code: string) => {
  const result = await authClient.twoFactor.verifyTotp({ code, trustDevice: false });
  if (result.error) throw new Error(result.error.message || "Unable to verify code.");
  await requireSuperAdmin("password");
};

/** @deprecated TOTP codes are generated by the user's authenticator app. */
export const resendSuperAdminEmailChallenge = async (): Promise<{ email: string | null }> => {
  throw new Error("Authenticator codes cannot be resent.");
};
