<template>
  <div class="page compliance-page">
    <RouterLink class="brand-mark" to="/" aria-label="ItemTraxx home">
      <img v-if="brandLogoUrl" class="brand-mark-full" :src="brandLogoUrl" alt="ItemTraxx Co" />
    </RouterLink>

    <main class="compliance-container">
      <div class="page-nav-left compliance-top-nav">
        <RouterLink class="compliance-back-link" to="/trust" aria-label="Return to trust center" @click.prevent="$router.back()">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M15 5 8 12l7 7" />
          </svg>
        </RouterLink>
        <span class="compliance-breadcrumb">Compliance</span>
      </div>

      <section class="compliance-hero">
        <p class="compliance-eyebrow">Security and compliance overview</p>
        <h1>Public compliance mappings backed by current security monitoring.</h1>
        <p class="compliance-lead">
          This page summarizes compliance-related control areas that are supported by the April 2026
          ItemTraxx Co security audit report generated by Aikido Security. We dont play around about security.
        </p>
        <div class="compliance-meta-grid" aria-label="Compliance report summary">
          <article>
            <span>Report date</span>
            <strong>April 2026</strong>
          </article>
          <article>
            <span>Aikido Security benchmark</span>
            <strong>Top 5%</strong>
          </article>
          <article>
            <span>Overdue SLA issues</span>
            <strong>0</strong>
          </article>
        </div>
      </section>

      <section class="compliance-section">
        <div class="compliance-section-header">
          <p class="compliance-section-label">Reported coverage</p>
          <h2>Current Coverage Areas</h2>
        </div>

        <div class="compliance-grid">
          <article v-for="item in complianceMappings" :key="item.title" class="compliance-card">
            <p class="compliance-card-kicker">{{ item.category }}</p>
            <h3>{{ item.title }}</h3>
            <p>{{ item.description }}</p>
            <ul class="compliance-list">
              <li v-for="measure in item.measures" :key="measure">{{ measure }}</li>
            </ul>
          </article>
        </div>
      </section>

      <section class="compliance-section">
        <div class="compliance-section-header">
          <p class="compliance-section-label">Remediation SLA</p>
          <h2>Configured vulnerability response targets.</h2>
          <p>
            The audit report shows zero issues outside configured SLA windows across all listed
            priority levels. We like to stay on top of things.
          </p>
        </div>

        <div class="sla-table" role="table" aria-label="Security issue remediation SLA compliance">
          <div class="sla-row sla-row-head" role="row">
            <span role="columnheader">Priority</span>
            <span role="columnheader">SLA</span>
            <span role="columnheader">Issues too late</span>
          </div>
          <div v-for="item in slaRows" :key="item.priority" class="sla-row" role="row">
            <span role="cell">{{ item.priority }}</span>
            <span role="cell">{{ item.sla }}</span>
            <strong role="cell">{{ item.late }}</strong>
          </div>
        </div>
      </section>

      <section class="compliance-note-card">
        <p class="compliance-section-label">Note</p>
        <h2>Compliance statements are intentionally conservative.</h2>
        <p>
          ItemTraxx does not publish the security audit report from this page. We do not claim
          SOC 2, ISO 27001, CIS, NIS2, ENS, NIST, or UK Cyber Essentials certification unless an
          applicable certification or attestation is available. This page is limited to reported
          active controls, framework mappings, and remediation status.
        </p>
        <RouterLink class="compliance-link" to="/contact-support">Ask a compliance question</RouterLink>
      </section>

      <PublicFooter />
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import { RouterLink } from "vue-router";
import PublicFooter from "../components/PublicFooter.vue";

const lightBrandLogoUrl = import.meta.env.VITE_BRAND_LOGO_LIGHT_URL as string | undefined;
const darkBrandLogoUrl = import.meta.env.VITE_BRAND_LOGO_DARK_URL as string | undefined;
const themeMode = ref<"light" | "dark">("dark");
const brandLogoUrl = computed(() =>
  themeMode.value === "light"
    ? lightBrandLogoUrl || darkBrandLogoUrl || ""
    : darkBrandLogoUrl || lightBrandLogoUrl || ""
);
let themeObserver: MutationObserver | null = null;

const complianceMappings = [
  {
    category: "Application security",
    title: "OWASP Top 10 active measures",
    description:
      "The audit report maps ItemTraxx controls against OWASP Top 10 risk categories with active measures in place.",
    measures: [
      "Access control and authorization protections",
      "Encryption of data at rest and secure connections",
      "Scanning and controls for SQL injection, XSS, CSRF, command injection, RCE, and SSRF",
      "Dependency lockfiles, secure deserialization measures, logging notifications, and email alerts",
    ],
  },
  {
    category: "Baseline controls",
    title: "UK Cyber Essentials mapped controls",
    description:
      "The audit report lists active measures across the five UK Cyber Essentials control areas.",
    measures: [
      "Public access restrictions for file storage, databases, and network resources",
      "Proper resource access management, encryption at rest, SSL/TLS controls, and secure cookie usage",
      "Identity verification for cloud users and protected runtime access",
      "Malware scanning posture, lockfiles, CI integration, and up-to-date runtimes",
    ],
  },
  {
    category: "Security operations",
    title: "CIS Controls v8.1 mapped controls",
    description:
      "The audit report lists active control mappings for data protection, logging, backups, and network restrictions.",
    measures: [
      "Least-privilege cloud access and data access control lists",
      "Encryption of sensitive data in transit and at rest",
      "Security logging for cloud instances and sensitive data access",
      "Automated backups for stateful cloud resources",
      "Restricted public access to databases, file storage, networks, and instances",
    ],
  },
  {
    category: "Operational resilience",
    title: "NIS2-aligned active measures",
    description:
      "The audit report identifies active measures relevant to risk policy, incident handling, supply chain hygiene, cryptography, and access control.",
    measures: [
      "Monitoring for code repositories, container images, public domains, and repository exposure",
      "Incident tracking through an issue tracker and configured remediation SLAs",
      "No issues outside SLA for applicable supply-chain security checks",
      "Safe SSL usage, secure cookies, up-to-date cryptographic libraries, and least-privilege cloud access",
    ],
  },
];

const slaRows = [
  { priority: "Critical", sla: "5 days", late: "0" },
  { priority: "High", sla: "20 days", late: "0" },
  { priority: "Medium", sla: "60 days", late: "0" },
  { priority: "Low", sla: "100 days", late: "0" },
];

onMounted(() => {
  const syncTheme = () => {
    themeMode.value = document.documentElement.getAttribute("data-theme") === "light" ? "light" : "dark";
  };

  syncTheme();
  themeObserver = new MutationObserver(syncTheme);
  themeObserver.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["data-theme"],
  });
});

onUnmounted(() => {
  if (themeObserver) {
    themeObserver.disconnect();
    themeObserver = null;
  }
});
</script>

<style scoped>
.compliance-page {
  max-width: 1120px;
  padding-top: calc(2rem + env(safe-area-inset-top, 0px));
}

.brand-mark {
  display: inline-flex;
  align-items: center;
  margin-bottom: 0.45rem;
  text-decoration: none;
}

.brand-mark-full {
  display: block;
  width: auto;
  height: 5.8rem;
  object-fit: contain;
}

.compliance-container {
  width: 100%;
}

.compliance-top-nav {
  display: flex;
  align-items: center;
  gap: 0.9rem;
  margin-bottom: 1.25rem;
}

.compliance-back-link {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 2.4rem;
  height: 2.4rem;
  border-radius: 999px;
  border: 1px solid var(--border);
  background: var(--surface);
  color: var(--text);
  text-decoration: none;
  transition: transform 0.16s ease, border-color 0.16s ease, background 0.16s ease;
}

.compliance-back-link:hover {
  transform: translateY(-1px);
  border-color: var(--text);
  background: var(--surface-2);
}

.compliance-back-link svg {
  width: 1rem;
  height: 1rem;
  fill: none;
  stroke: currentColor;
  stroke-linecap: round;
  stroke-linejoin: round;
  stroke-width: 2;
}

.compliance-breadcrumb,
.compliance-eyebrow,
.compliance-section-label,
.compliance-card-kicker {
  text-transform: uppercase;
  letter-spacing: 0.12em;
  font-size: 0.76rem;
  font-weight: 700;
  color: color-mix(in srgb, var(--text) 64%, var(--accent) 36%);
}

.compliance-hero,
.compliance-card,
.compliance-note-card {
  border: 1px solid color-mix(in srgb, var(--border) 58%, transparent);
  border-radius: 1rem;
  background: transparent;
  box-shadow: none;
}

.compliance-hero {
  padding: clamp(2rem, 4vw, 3.2rem);
  margin-bottom: 1.5rem;
}

.compliance-hero h1,
.compliance-section-header h2,
.compliance-card h3,
.compliance-note-card h2 {
  margin: 0;
  line-height: 1.05;
  letter-spacing: -0.04em;
}

.compliance-hero h1 {
  max-width: 52rem;
  margin-top: 0.8rem;
  font-size: clamp(1.65rem, 4vw, 3.05rem);
}

.compliance-lead,
.compliance-section-header p,
.compliance-card p,
.compliance-list,
.compliance-note-card p {
  color: color-mix(in srgb, var(--text) 84%, transparent);
  line-height: 1.72;
}

.compliance-lead {
  max-width: 52rem;
  margin: 1.2rem 0 0;
  font-size: 1.02rem;
}

.compliance-meta-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 1rem;
  margin-top: 1.6rem;
}

.compliance-meta-grid article {
  display: grid;
  gap: 0.35rem;
  padding: 1rem;
  border: 1px solid color-mix(in srgb, var(--border) 52%, transparent);
  border-radius: 0.85rem;
}

.compliance-meta-grid span {
  color: color-mix(in srgb, var(--text) 58%, transparent);
  font-size: 0.84rem;
}

.compliance-meta-grid strong {
  font-size: 1.35rem;
}

.compliance-section {
  margin-top: 1.5rem;
}

.compliance-section-header {
  max-width: 52rem;
  margin-bottom: 1rem;
}

.compliance-section-header h2 {
  margin-top: 0.5rem;
  font-size: clamp(1.3rem, 2.8vw, 2.1rem);
}

.compliance-section-header p {
  margin: 0.8rem 0 0;
}

.compliance-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 1rem;
}

.compliance-card {
  padding: 1.45rem;
}

.compliance-card h3 {
  margin-top: 0.55rem;
  font-size: 1.35rem;
}

.compliance-card p {
  margin: 0.8rem 0 0;
}

.compliance-list {
  display: grid;
  gap: 0.55rem;
  margin: 1rem 0 0;
  padding-left: 1.15rem;
}

.sla-table {
  overflow: hidden;
  border: 1px solid color-mix(in srgb, var(--border) 58%, transparent);
  border-radius: 1rem;
}

.sla-row {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 1rem;
  padding: 0.95rem 1rem;
  border-top: 1px solid color-mix(in srgb, var(--border) 46%, transparent);
}

.sla-row:first-child {
  border-top: 0;
}

.sla-row-head {
  color: color-mix(in srgb, var(--text) 62%, transparent);
  font-size: 0.78rem;
  font-weight: 700;
  letter-spacing: 0.1em;
  text-transform: uppercase;
}

.sla-row strong {
  color: color-mix(in srgb, var(--text) 64%, var(--accent) 36%);
}

.compliance-note-card {
  margin-top: 1.5rem;
  padding: clamp(1.35rem, 3vw, 1.8rem);
}

.compliance-note-card h2 {
  margin-top: 0.55rem;
  font-size: clamp(1.2rem, 2.4vw, 1.8rem);
}

.compliance-link {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 2.45rem;
  padding: 0.55rem 1rem;
  margin-top: 1rem;
  border: 1px solid color-mix(in srgb, var(--border) 72%, transparent);
  border-radius: 999px;
  background: color-mix(in srgb, var(--surface-2) 68%, transparent);
  color: color-mix(in srgb, var(--text) 62%, var(--accent) 38%);
  font-weight: 700;
  text-decoration: none;
}

@media (max-width: 840px) {
  .compliance-meta-grid,
  .compliance-grid {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 640px) {
  .compliance-page {
    padding-top: calc(1.25rem + env(safe-area-inset-top, 0px));
  }

  .brand-mark-full {
    height: 3.9rem;
  }

  .sla-row {
    grid-template-columns: 1fr;
    gap: 0.25rem;
  }
}
</style>
