// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/vue'

import _admin_borrowers_table from './admin-borrowers-table.bones.json'
import _admin_archived_borrowers_table from './admin-archived-borrowers-table.bones.json'
import _admin_borrowers_table_bulk from './admin-borrowers-table-bulk.bones.json'
import _admin_item_logs_table from './admin-item-logs-table.bones.json'
import _super_admin_logs_table from './super-admin-logs-table.bones.json'

configureBoneyard({"color":"#e9e9e3","darkColor":"#282824","animate":"shimmer"})

registerBones({
  "admin-borrowers-table": _admin_borrowers_table,
  "admin-archived-borrowers-table": _admin_archived_borrowers_table,
  "admin-borrowers-table-bulk": _admin_borrowers_table_bulk,
  "admin-item-logs-table": _admin_item_logs_table,
  "super-admin-logs-table": _super_admin_logs_table,
})
