# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v6
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  notify-slack-on-failure:
    needs: label
    if: ${{ always() && needs.label.result == 'failure' }}
    uses: ./.github/workflows/slack-notify-failure.yml
    with:
      workflow_name: Labeler
      job_name: label
      run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      ref_name: ${{ github.ref_name }}
      sha: ${{ github.sha }}
    secrets: inherit
